
#web:
#  upload-path: D:/file/
#  fornt-path: D:/fornt/

server:
  port: 8011
  servlet:
#    context-path: /api
    session:
      timeout: 15m
spring:
  datasource:
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/db_wt?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    &allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
#  resources:
#    static-locations: file:${web.upload-path},file:${web.fornt-path}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shhy.demo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql