
#web:
#  upload-path: D:/file/
#  fornt-path: D:/fornt/

server:
  port: 8011
  servlet:
#    context-path: /api
    session:
      timeout: 10m
spring:
  datasource:
    username: wtdbuser
    password: wtdbuser
    url: jdbc:mysql://bj-cdb-hgkqwllz.sql.tencentcdb.com:63308/wt-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
#  resources:
#    static-locations: file:${web.upload-path},file:${web.fornt-path}

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.shhy.demo.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql